name: Create torrent
on:
  push:
    branches:
      - master
      
env:
  name: "Vinay Photos"
  comment: "The comment inside the torrent file."
  url: "https://doc-6k-38-photos-data-export.googleusercontent.com/download/svtessdck3to19jl39klha1nboqq9cm8/f10cl1kro7b56mgonoqto6vp3rm8qd06/1751296500000/f6126d01-bbe3-442f-9ef9-a9b661f9251e/105765626431716220259/ADt3v-Og-uQb3H3DwRwc7k-t4cqbxFP106RRTx-JBb1zF9c_-_c4zFwp09eUCy_HpUDiJgbsAGETYb6TjEUhT2UiWoXwGFFw_f8HYuX_-ID1tNorZfXrzr_3iW2aW236JlSxROqrIECGDznQuvzHWSeZRmNL-o3-A2-Fhhrjbn4TOfH7tRKP3EkXD_rpjeDi0M88W6Nw9eRZgijIApHK7F0YThYWKCjsiJcg5cbeQsC-5bx4CuZG6lCdh28K6DcIzqY4xSKPF0jCt3JdXHauvpW8mPwtp8M6nS0gpRqaCArK_elEcZfVqqM=?authuser=0&nonce=iruu8clbp41tq&user=105765626431716220259&hash=sc7g07jucltg6tjf09lkp03phkb9l1a5"
  file_name: "Vinay Photos"
  piece_size: The size of the torrent pieces in potency of 2 (2^n)
      
jobs:
  create:
    runs-on: ubuntu-20.04
    steps:
      - name: Install mktorrent
        run: sudo apt-get install mktorrent
        
      - name: Download file
        run: wget -nv -O "$file_name" "$url"
        
      - name: Create torrent using mktorrent
        run: mktorrent -c "$comment" -l $piece_size -o "${name}.torrent" -w "$url" "$file_name"
        
      - name: Upload torrent file
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.name }}
          path: ${{ env.name }}.torrent
